# Specifies the JVM used by Gradle Daemon to Android Studio's bundled JDK 21
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
android.useAndroidX=true
android.enableJetifier=true
hermesEnabled=true
newArchEnabled=false
org.gradle.dependency.verification=off
